### ISSUE TITLE
Wrong text parsing

### ISSUE THREAD

**Issue by bclaise** [oscargdd/draft-ogondio-opsawg-isis-topology#16]
Also, should the topology include information such as bandwidth,
   delay information or color, it must include tet:te-topology.  To
   include delay and bandwdith performance measurements , MUST include
   tet-pkt:te-packet under the previous property The supporting-network
   property can include the network-id of a base layer-3 network.  The
   node property should include the list of nodes as described below.
   The ietf-network-topology:link MUST be present, with one link per
   each IP adjacency (one link for each direction of the adjancency).

There is something with the parsing of the above.
Since I am not the author, I'll flag this as an issue here

**Comment by bclaise** [comment]
Also, what is this "tet" prefix YANG module. I guess you mean: RFC 8795.
It's just weird to include the prefix in the text. I'll improve the text to include RFC 8795.




</body>
</html>

**Comment by bclaise** [comment]
And which YANG model does this "MUST include tet-pkt:te-packet under the previous property" refer to?   Something around https://datatracker.ietf.org/doc/draft-ietf-teas-yang-l3-te-topo/15/ ? It's not clear

**Comment by sbarguil** [comment]
> Also, what is this "tet" prefix YANG module. I guess you mean: RFC 8795. It's just weird to include the prefix in the text. I'll improve the text to include RFC 8795.

yep I agree dont know why the references come in that way. But "tet" refers to RFC 8795. and the "tet-pkt" to draft-ietf-teas-yang-l3-te-topo.
