### ISSUE TITLE
Paragraph on simulation and on use cases

### ISSUE THREAD

**Issue by ppavon** [oscargdd/draft-ogondio-opsawg-isis-topology#8]
As requested by Oscar, I include below some paragraphs related to the simulation / capacity planning and other use cases, potentially to include in a use cases section. Please see below some suggested writing:

The standardization of the NBI of SDN controllers for IP networks, permits the connection of third party tools covering specialized cases. Among them, the tools for network performance optimization, and network dimensioning and planning would benefit from retrieving from the NBI an abstracted view of the IP network topology and IGP configurations. 

As for IS-IS, the NBI should export enough information to permit these tools simulating the IP routing at a macroscopic flow level. That is, simulating how IP-level traffic demands would be forwarded, after ISIS convergence is reached, and from there estimating, using appropriate mathematical models, related KPIs like the occupation in the links or end-to-end latencies. 

Being able to simulate the IP demands routing, enables multiple use cases like:

* What-if analysis. Estimation of the network KPIs in modified network situations. For instance, failure situations, traffic anomaly situations, addition or deletion of new adjacencies, IGP weight reconfigurations.
* Failure analysis. Systematic and massive test of the network under multiple simulated failure situations, evaluating the network fault tolerance properties, and using mathematical models to derive statistical network availability metrics.
* Network design & capacity planning. Dimensioning or redesign of the IP infrastructure to satisfy target KPI metrics under existing or forecasted traffic demands.

**Comment by bclaise** [comment]
In order to speed up the process, I took the freedom to take your proposal into account, modify it, add some other sections in the second commit of https://github.com/oscargdd/draft-ogondio-opsawg-isis-topology/pull/11/commits

**Comment by oscargdd** [comment]
Closed as included  by Benoit
